# Basic
title: 徐钟天的个人博客
subtitle: 天地本无心
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
welcome_message: 不想当厨子的生物学家不是好黑客
description: 凡是过往 皆为序章
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:  slate

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
        #- {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
        #- {title: publication, description: My publication, url: 'http://baidu.com'}
        - {title: Archive, description: select paper by time, url: 'http://baidu.com'}
        - {title: Tag, description: select paper by Tag, url: 'http://baidu.com'}
        - {title: Resume, description: My resume, url: 'http://baidu.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
        #weibo: wandering513
    github: wandering513
    twitter: wandering513
    gplus: 107108267983477358170
    mail: xuzhongtian11@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
